import time
import random
import pyautogui

def enterGameAndFinishTutorial():

    sex = random.randint(1, 2)

    if sex == 1:
        pyautogui.moveTo(415, 510)
        time.sleep(0.1)
        pyautogui.click()
    if sex == 2:
        pyautogui.moveTo(1505, 425)
        time.sleep(0.1)
        pyautogui.click()

    time.sleep(2)
    pyautogui.moveTo(960, 990)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.write('jasp')
    time.sleep(0.1)
    pyautogui.moveTo(1700, 990)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(15)

    while not pyautogui.pixelMatchesColor(1756, 59, (255, 255, 255)):
        time.sleep(2)
        pyautogui.press('esc')
        time.sleep(2)
    time.sleep(1)
    pyautogui.keyDown('alt')
    time.sleep(0.1)
    pyautogui.moveTo(210, 480)
    time.sleep(0.1)
    pyautogui.drag(1640, 510, 1)
    time.sleep(0.1)
    pyautogui.keyUp('alt')
    time.sleep(0.1)
    pyautogui.press('`')
    time.sleep(1)
    pyautogui.moveTo(170, 760)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(0.3)
    pyautogui.moveTo(435, 595)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.press('`')

    for i in range(1, 6):
        pyautogui.press('up')
        time.sleep(4.3)
    time.sleep(1)
    pyautogui.press('f')
    while not pyautogui.pixelMatchesColor(730, 560, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(2)
    pyautogui.click()
    time.sleep(0.5)

    for i in range(1, 5):
        pyautogui.press('up')
        time.sleep(2)
    for i in range(1, 8):
        pyautogui.press('up')
        time.sleep(1.8)
    pyautogui.keyDown('w')
    time.sleep(2)
    pyautogui.keyUp('w')
    time.sleep(3)
    while not pyautogui.pixelMatchesColor(1756, 59, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(1.5)

    for i in range(1, 64):
        pyautogui.press('up')
        time.sleep(0.37)

    time.sleep(3)
    for i in range(1, 4):
        pyautogui.press('up')
        time.sleep(1.5)
    while not pyautogui.pixelMatchesColor(1842, 47, (59, 66, 85)):
        time.sleep(0.5)
    time.sleep(1)
    pyautogui.moveTo(1842, 47)
    time.sleep(0.3)
    pyautogui.click()
    time.sleep(10)

    pyautogui.press('q')
    time.sleep(7.5)

    pyautogui.keyDown('a')
    time.sleep(0.5)
    pyautogui.keyUp('a')
    time.sleep(0.3)
    pyautogui.keyDown('w')
    time.sleep(0.35)
    pyautogui.keyUp('w')
    time.sleep(1)
    pyautogui.press('e')
    time.sleep(1)
    time.sleep(1)
    pyautogui.keyDown('e')
    time.sleep(2)
    pyautogui.keyUp('e')
    time.sleep(2.5)
    pyautogui.press('q')
    time.sleep(4)

def fromFirstStatueToDungsQuests():
    pyautogui.press('up')
    time.sleep(2)
    pyautogui.press('up')
    time.sleep(1)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(10)
    pyautogui.press('up')
    time.sleep(3)
    while not pyautogui.pixelMatchesColor(1756, 59, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(3)
    pyautogui.press('up')
    time.sleep(3)
    pyautogui.press('up')
    time.sleep(2)
    pyautogui.press('f')
    time.sleep(1)
    while not pyautogui.pixelMatchesColor(1756, 59, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(1)


    pyautogui.press('up')
    time.sleep(1)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(1)
    pyautogui.press('up')
    time.sleep(1)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(4)
    while not pyautogui.pixelMatchesColor(320, 670, (255, 204, 50)):
        time.sleep(0.3)
    time.sleep(1)
    pyautogui.click()
    time.sleep(2.5)
    pyautogui.press('2')
    time.sleep(1)
    pyautogui.press('r')
    time.sleep(1)
    pyautogui.press('r')
    time.sleep(1.5)
    pyautogui.press('f6')
    time.sleep(1)
    pyautogui.press('up')
    time.sleep(1.5)
    pyautogui.press('up')
    time.sleep(1)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(1)
    pyautogui.press('down')
    time.sleep(1)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(1)
    for i in range(1, 6):
        pyautogui.click()
        time.sleep(1)


    pyautogui.press('up')
    time.sleep(1)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(1)
    pyautogui.press('f')
    time.sleep(1)
    pyautogui.press('up')
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(1.5)
    pyautogui.click()
    time.sleep(1.5)
    pyautogui.press('up')
    time.sleep(2)
    pyautogui.press('up')
    time.sleep(2)
    pyautogui.press('up')
    time.sleep(2)
    while pyautogui.pixelMatchesColor(1864, 363, (255, 255, 255)):
        pyautogui.click()
        time.sleep(1.2)
    while not pyautogui.pixelMatchesColor(1864, 363, (255, 255, 255)):
        time.sleep(0.5)
    time.sleep(0.3)
    pyautogui.press('up')


    time.sleep(1)
    pyautogui.press('up')
    time.sleep(1)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(1)
    pyautogui.press('f')
    time.sleep(1)
    pyautogui.press('up')
    time.sleep(2)
    pyautogui.press('f')
    while not pyautogui.pixelMatchesColor(1864, 363, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(3)
    pyautogui.keyDown('w')
    time.sleep(0.7)
    pyautogui.keyUp('w')
    time.sleep(1)
    pyautogui.press('f')
    time.sleep(2)
    pyautogui.moveTo(1660, 1020)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(975, 1025)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(1.5)
    pyautogui.moveTo(963, 925)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(2)
    pyautogui.click()
    time.sleep(2)
    pyautogui.press('esc')
    time.sleep(2)
    pyautogui.press('up')
    time.sleep(1)
    pyautogui.press('f')
    time.sleep(1)
    while not pyautogui.pixelMatchesColor(1864, 363, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(0.5)


    pyautogui.press('up')
    time.sleep(1.5)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(9)
    pyautogui.press('j')
    time.sleep(1.5)
    pyautogui.press('esc')
    time.sleep(1.5)
    while not pyautogui.pixelMatchesColor(1756, 59, (255, 255, 255)):
        time.sleep(0.1)
    time.sleep(1)
    pyautogui.press('up')
    time.sleep(1)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(1)
    pyautogui.keyDown('w')
    time.sleep(1.5)
    pyautogui.keyUp('w')
    time.sleep(3)
    while not pyautogui.pixelMatchesColor(1861, 462, (255, 255, 255)):
        time.sleep(0.5)
    time.sleep(1)
    pyautogui.keyDown('w')
    time.sleep(0.7)
    pyautogui.keyUp('w')
    time.sleep(0.5)
    pyautogui.press('space')
    time.sleep(1)
    pyautogui.press('up')
    time.sleep(1)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(1)
    pyautogui.keyDown('s')
    time.sleep(2)
    pyautogui.keyUp('s')


    time.sleep(2)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    while not pyautogui.pixelMatchesColor(960, 540, (255, 255, 255)):
        time.sleep(0.5)
    pyautogui.press('f7')
    time.sleep(1)
    pyautogui.mouseDown()
    while pyautogui.pixelMatchesColor(960, 540, (255, 255, 255)):
        time.sleep(1)
    pyautogui.mouseUp()
    time.sleep(2)
    while not pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(2)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(2)
    while not pyautogui.pixelMatchesColor(1861, 462, (255, 255, 255)):
        time.sleep(0.5)
    time.sleep(2)
    pyautogui.press('up')
    time.sleep(1)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(2)
    pyautogui.press('f')
    time.sleep(2)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(1)
    while not pyautogui.pixelMatchesColor(1861, 462, (255, 255, 255)):
        time.sleep(1)
    time.sleep(1)
    pyautogui.press('up')
    time.sleep(1)
    pyautogui.press('f')
    time.sleep(1)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(1)

def threeDungeons():
    pyautogui.press('up')
    time.sleep(1)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(1)
    pyautogui.press('f')
    time.sleep(1)
    while not pyautogui.pixelMatchesColor(1861, 462, (255, 255, 255)):
        time.sleep(0.3)
    pyautogui.press('up')
    time.sleep(1)
    pyautogui.press('f')
    time.sleep(3)
    pyautogui.moveTo(1700, 1010)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(2)
    pyautogui.click()
    time.sleep(1)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(2)
    pyautogui.press('up')
    time.sleep(1)
    pyautogui.press('f')
    time.sleep(3)
    pyautogui.press('f8')
    time.sleep(1)
    pyautogui.press('up')
    time.sleep(2)
    pyautogui.click()
    time.sleep(2)
    pyautogui.click()
    time.sleep(1)
    for i in range(1, 7):
        pyautogui.press('up')
        time.sleep(3.5)
    pyautogui.press('f8')
    time.sleep(1)
    pyautogui.press('up')
    time.sleep(1)
    pyautogui.click()
    time.sleep(1)
    pyautogui.click()
    time.sleep(2)
    while not pyautogui.pixelMatchesColor(1861, 462, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(1)
    pyautogui.press('up')
    time.sleep(1.5)
    pyautogui.press('up')
    time.sleep(1)
    pyautogui.press('f')
    time.sleep(2)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(2)


    pyautogui.press('up')
    time.sleep(1)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(2)
    pyautogui.press('f')
    time.sleep(1)
    while not pyautogui.pixelMatchesColor(1861, 462, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(1)
    pyautogui.press('up')
    time.sleep(1)
    pyautogui.press('f')
    time.sleep(3)
    pyautogui.moveTo(1700, 1010)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(2)
    pyautogui.click()
    time.sleep(1)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(2)
    pyautogui.press('up')
    time.sleep(4)
    pyautogui.press('f8')
    time.sleep(1)
    pyautogui.press('up')
    time.sleep(3)
    for i in range(1, 7):
        pyautogui.press('up')
        time.sleep(4)
    pyautogui.press('f8')
    time.sleep(2)
    pyautogui.press('up')
    time.sleep(3)
    pyautogui.click()
    time.sleep(3)
    while not pyautogui.pixelMatchesColor(320, 670, (255, 204, 50)):
        time.sleep(0.5)
    time.sleep(3)
    pyautogui.click()


    time.sleep(1)
    pyautogui.press('up')
    time.sleep(2)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(2)
    pyautogui.press('f')
    time.sleep(1)
    while not pyautogui.pixelMatchesColor(1861, 410, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(1)
    pyautogui.press('up')
    time.sleep(1)
    pyautogui.press('f')
    time.sleep(3)
    pyautogui.moveTo(1700, 1010)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(2)
    pyautogui.click()
    time.sleep(1)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(2)
    pyautogui.press('up')
    time.sleep(3)
    pyautogui.press('f8')
    time.sleep(1)
    pyautogui.press('up')
    time.sleep(4)
    for i in range(1, 7):
        pyautogui.press('up')
        time.sleep(3.5)
    time.sleep(1)
    pyautogui.press('f8')
    time.sleep(1)
    pyautogui.press('up')
    time.sleep(1)
    pyautogui.click()
    time.sleep(1)
    pyautogui.click()
    time.sleep(1.5)
    pyautogui.press('f')
    time.sleep(5)
    while not pyautogui.pixelMatchesColor(1861, 410, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(1)
    pyautogui.press('up')
    time.sleep(1)
    pyautogui.press('up')
    time.sleep(1)
    pyautogui.press('f')
    time.sleep(2)
    while not pyautogui.pixelMatchesColor(320, 670, (255, 204, 50)):
        time.sleep(0.5)
    time.sleep(4)
    pyautogui.click()
    time.sleep(3)
    while not pyautogui.pixelMatchesColor(836, 364, (255, 233, 0)):
        time.sleep(0.5)
    time.sleep(2)
    pyautogui.click()
    while not pyautogui.pixelMatchesColor(967, 394, (241, 255, 139)):
        time.sleep(0.5)
    time.sleep(1)
    pyautogui.click()
    time.sleep(2)
    while not pyautogui.pixelMatchesColor(836, 364, (255, 233, 0)):
        time.sleep(0.5)
    time.sleep(2)
    pyautogui.click()
    while not pyautogui.pixelMatchesColor(967, 394, (241, 255, 139)):
        time.sleep(0.5)
    time.sleep(1)
    pyautogui.click()
    time.sleep(3)

def teleports():
    for i in range(1, 7):
        pyautogui.press('up')
        time.sleep(2)
        while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
            time.sleep(0.3)
        time.sleep(3)
        pyautogui.press('f')
        time.sleep(1)
    pyautogui.press('up')
    time.sleep(2)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(3)
    pyautogui.press('f')
    time.sleep(1)
    while not pyautogui.pixelMatchesColor(1842, 47, (59, 66, 85)):
        time.sleep(0.5)
    time.sleep(1)
    pyautogui.moveTo(1842, 47)
    time.sleep(0.3)
    pyautogui.click()
    time.sleep(1)
    pyautogui.click()
    time.sleep(3)
    pyautogui.press('esc')
    time.sleep(2)


    for i in range(1, 3):
        pyautogui.press('up')
        time.sleep(2)
        while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
            time.sleep(0.3)
        time.sleep(2)
        pyautogui.press('f')
        time.sleep(1)
    pyautogui.press('up')
    time.sleep(2)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(2)
    pyautogui.press('f')
    time.sleep(1)
    while not pyautogui.pixelMatchesColor(1842, 47, (59, 66, 85)):
        time.sleep(0.5)
    time.sleep(1)
    pyautogui.moveTo(1842, 47)
    time.sleep(0.3)
    pyautogui.click()
    time.sleep(1)
    pyautogui.click()
    time.sleep(3)
    pyautogui.press('esc')
    time.sleep(2)


    for i in range(1, 7):
        pyautogui.press('up')
        time.sleep(2)
        while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
            time.sleep(0.3)
        time.sleep(2)
        pyautogui.press('f')
        time.sleep(1)
    pyautogui.press('up')
    time.sleep(2)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(2)
    pyautogui.press('f')
    time.sleep(1)
    while not pyautogui.pixelMatchesColor(1842, 47, (59, 66, 85)):
        time.sleep(0.5)
    time.sleep(1)
    pyautogui.moveTo(1842, 47)
    time.sleep(0.3)
    pyautogui.click()
    time.sleep(1)
    pyautogui.click()
    time.sleep(3)
    pyautogui.press('esc')
    time.sleep(2)


    for i in range(1, 7):
        pyautogui.press('up')
        time.sleep(2)
        while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
            time.sleep(0.3)
        time.sleep(2)
        pyautogui.press('f')
        time.sleep(1)
    time.sleep(2)

def anemoculuses():
    time.sleep(2)
    for i in range(1, 38):
        pyautogui.press('up')
        time.sleep(2)
        while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
            time.sleep(0.3)
        time.sleep(1.6)

def chests():
    time.sleep(2)
    for i in range(1, 29):
        pyautogui.press('up')
        time.sleep(2)
        while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
            time.sleep(0.3)
        time.sleep(1.6)
    time.sleep(4)
    for i in range(1, 16):
        pyautogui.press('up')
        time.sleep(2)
        while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
            time.sleep(0.3)
        time.sleep(1.6)

def finish10LV():
    time.sleep(2)
    pyautogui.press('f')
    while not pyautogui.pixelMatchesColor(1298, 718, (255, 255, 255)):
        time.sleep(0.3)
    pyautogui.moveTo(1298, 718)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(1.5)
    pyautogui.moveTo(1298, 800)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1552, 1023)
    time.sleep(0.1)
    for i in range(1, 7):
        time.sleep(1)
        pyautogui.click()
        time.sleep(1)
        pyautogui.click()
    time.sleep(1)
    pyautogui.press('esc')
    time.sleep(1.5)
    pyautogui.moveTo(1298, 718)
    time.sleep(0.1)
    pyautogui.click()
    while not pyautogui.pixelMatchesColor(1861, 362, (255, 255, 255)):
        time.sleep(0.3)


    pyautogui.press('m')
    time.sleep(1.5)
    pyautogui.moveTo(1192, 741)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.moveTo(1678, 1006)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(2)
    while pyautogui.pixelMatchesColor(950, 230, (255, 255, 255)):
        time.sleep(0.3)
    time.sleep(2)
    pyautogui.keyDown('s')
    time.sleep(1.5)
    pyautogui.keyUp('s')
    time.sleep(0.3)
    pyautogui.press('f')
    time.sleep(3)
    pyautogui.moveTo(1751, 1023)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(5)
    pyautogui.press('esc')
    time.sleep(2)


    pyautogui.press('c')
    time.sleep(2)
    pyautogui.moveTo(231, 225)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(1.5)
    pyautogui.moveTo(1720, 1005)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(2)
    pyautogui.moveTo(1748, 764)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.moveTo(1720, 1005)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(4)
    pyautogui.moveTo(960, 832)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(1)
    pyautogui.press('esc')
    time.sleep(2)
    pyautogui.moveTo(272, 298)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(1.5)
    pyautogui.moveTo(1615, 1000)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(1)
    x = 88
    for i in range(1, 6):
        pyautogui.moveTo(x, 44)
        time.sleep(0.1)
        pyautogui.click()
        time.sleep(1)
        pyautogui.moveTo(1545, 1005)
        time.sleep(0.1)
        pyautogui.click()
        time.sleep(1)
        x += 110
    time.sleep(1)
    pyautogui.press('esc')
    time.sleep(1)
    pyautogui.press('esc')
    time.sleep(2)


    pyautogui.press('f1')
    time.sleep(2)
    for i in range(1, 5):
        pyautogui.moveTo(1511, 326)
        time.sleep(0.1)
        pyautogui.click()
        time.sleep(1)
        pyautogui.click()
        time.sleep(1)
    pyautogui.moveTo(556, 853)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(1)
    pyautogui.click()
    time.sleep(4)
    for i in range(1, 6):
        pyautogui.moveTo(1511, 326)
        time.sleep(0.1)
        pyautogui.click()
        time.sleep(1)
        pyautogui.click()
        time.sleep(1)
    time.sleep(1)
    pyautogui.press('esc')

def do10Roll():
    pyautogui.moveTo(1630, 1000)
    time.sleep(0.2)
    pyautogui.click()
    time.sleep(0.2)
    gemCheck = pyautogui.pixelMatchesColor(1050, 750, (74, 83, 102))
    if gemCheck:
        pyautogui.press("esc")
        time.sleep(0.3)
    else:
        time.sleep(2)
        pyautogui.moveTo(1790, 40)
        time.sleep(0.3)
        pyautogui.click()
        time.sleep(0.3)
        pyautogui.click()



        time.sleep(1)
        pyautogui.moveTo(1840, 45)
        time.sleep(0.1)
        pyautogui.click()
        time.sleep(0.75)
